# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Java
        run: |
          # Install xml2 -------------------------------------------------------
          install.packages("xml2", type = "binary")
          # Get URL to current Windows binary ----------------------------------
          page   <- xml2::read_html("https://jdk.java.net/15/")
          anchor <- xml2::xml_find_all(page, "//blockquote//table//td//a")
          links  <- xml2::xml_attr(anchor, "href")
          url    <- links[grepl("(?i)win", links) & !grepl("(?i)sha256", links)]
          # Download JDK -------------------------------------------------------
          zip_path <- "~/openjdk.zip"
          download.file(url, destfile = zip_path, quiet = TRUE, mode = "wb")
          # Extract and rename JDK directory -----------------------------------
          unzip(zip_path, exdir = "~")
          jdk_dir <- list.files("~", pattern = "(?i)^jdk")
          file.rename(jdk_dir, "openjdk")
          # Set JAVA_HOME ------------------------------------------------------
          j_home        <- gsub("/", "\\\\", path.expand("~/openjdk"))
          set_java_home <- paste0('setx JAVA_HOME ', '"', j_home, '"')
          system(set_java_home)
          # Add JAVA_HOME/bin to path ------------------------------------------
          sys_path <- Sys.getenv("Path")
          p_end    <- if (!grepl(";$", sys_path)) "" else ";"
          new_path <- paste0(sys_path, p_end, j_home, "\\bin;")
          set_path <- paste0('setx Path ', '"', new_path, '"')
          system(set_path)
        shell: Rscript {0}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), type = "binary")
          remotes::install_github(
            "socialresearchcentre/dialr",
            INSTALL_opts = "--no-multiarch"
          )
          remotes::install_deps(dependencies = TRUE, type = "binary")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
